---
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: nginx-member2
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: nginx
  targetCluster:
    clusterNames:
      - dev-cluster-02
  overriders:
    plaintext:
      - path: "/spec/ordinals/start"
        operator: replace
        value: 3