apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: prometheus-rbac
  namespace: monitoring
spec:
  resourceSelectors:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: prometheus
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: prometheus
  placement:
    clusterAffinity:
      clusterNames:
        - member4
        - member5