apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: node-exporter
    - apiVersion: apps/v1
      kind: DaemonSet
      name: node-exporter
  placement:
    clusterAffinity:
      clusterNames:
        - member4
        - member5