---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.25.1
  name: thanos-service
  namespace: monitoring
spec:
  ports:
    - port: 10901
      protocol: TCP
      targetPort: 10901
  selector:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: thanos-service
  namespace: monitoring
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: service-export-member4
  namespace: monitoring
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: thanos-service
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceExport
      name: thanos-service
  placement:
    clusterAffinity:
      clusterNames:
        - member4