---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.25.1
  name: thanos-receive
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: grpc
    - name: http
      port: 10902
      protocol: TCP
      targetPort: http
    - name: remote-write
      port: 19291
      protocol: TCP
      targetPort: remote-write
  selector:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive