apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: thanos-query
    - apiVersion: apps/v1
      kind: Deployment
      name: thanos-query
  placement:
    clusterAffinity:
      clusterNames:
        - member5