apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: thanos-rule
    app.kubernetes.io/name: thanos-rule
    app.kubernetes.io/version: v0.25.1
  name: thanos-rule
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
    - name: http
      port: 10902
      targetPort: 10902
    - name: reloader
      port: 9533
      targetPort: 9533
  selector:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: thanos-rule
    app.kubernetes.io/name: thanos-rule
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: thanos-rule
    app.kubernetes.io/name: thanos-rule
    app.kubernetes.io/version: v0.25.1
  name: thanos-rule
  namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rules
  namespace: monitoring
  labels:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: thanos-rule
    app.kubernetes.io/name: thanos-rule
    app.kubernetes.io/version: v0.23.1
data:
  rules.yml: |-
    groups:
    - name: Linux
      rules:
      - alert: 测试告警-磁盘空间利用率大于30
        expr: ceil(((node_filesystem_size_bytes - node_filesystem_avail_bytes) /node_filesystem_size_bytes) * 100) > 30
        for: 1m
        labels:
          severity: 一般告警
        annotations:
          summary: "文件系统:{{ .Labels.mountpoint }} 使用率过高"
          description: "{{$labels.instance}}: 当前文件系统使用率大于30%，使用率为: {{ $value }}"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: thanos-rule
    app.kubernetes.io/name: thanos-rule
    app.kubernetes.io/version: v0.25.1
  name: thanos-rule
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: rule-evaluation-engine
      app.kubernetes.io/instance: thanos-rule
      app.kubernetes.io/name: thanos-rule
  serviceName: thanos-rule
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rule-evaluation-engine
        app.kubernetes.io/instance: thanos-rule
        app.kubernetes.io/name: thanos-rule
        app.kubernetes.io/version: v0.25.1
    spec:
      containers:
        - args:
            - rule
            - --log.level=info
            - --log.format=logfmt
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --data-dir=/var/thanos/rule
            - --label=rule_replica="$(NAME)"
            - --alert.label-drop=rule_replica
            - --tsdb.retention=48h
            - --tsdb.block-duration=2h
            - --query=dnssrv+_http._tcp.thanos-query.monitoring.svc.cluster.local
            - --alertmanagers.url=http://alertmanager.monitoring.svc.cluster.local:9093
            - --rule-file=/etc/thanos/rules/rule.d/rules.yml
            - |-
              --tracing.config="config":
                "sampler_param": 2
                "sampler_type": "ratelimiting"
                "service_name": "thanos-rule"
              "type": "JAEGER"
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: quay.io/thanos/thanos:v0.25.1
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: /-/healthy
              port: 10902
              scheme: HTTP
            periodSeconds: 5
          name: thanos-rule
          ports:
            - containerPort: 10901
              name: grpc
            - containerPort: 10902
              name: http
            - containerPort: 9533
              name: reloader
          readinessProbe:
            failureThreshold: 18
            httpGet:
              path: /-/ready
              port: 10902
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 0.42
              memory: 420Mi
            requests:
              cpu: 0.123
              memory: 123Mi
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /var/thanos/rule
              name: data
              readOnly: false
            - mountPath: /etc/thanos/rules/rule.d
              name: rules
        - args:
            - -webhook-url=http://localhost:10902/-/reload
            - -volume-dir=/etc/thanos/rules/rule.d
          image: jimmidyson/configmap-reload:v0.5.0
          name: configmap-reloader
          volumeMounts:
            - mountPath: /etc/thanos/rules/rule.d
              name: rules
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      serviceAccountName: thanos-rule
      volumes:
        - configMap:
            name: rules
          name: rules
        - name: data
          emptyDir: {}